version: '3.4'

services:
    api-compras: 
        image: api-compras
        build: 
            context: ./ApiCompras
            dockerfile: Dockerfile
        ports: 
            - 6000:80
            - 6001:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development 
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=tuk1
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.vsdbg:/remote_debbuger.rw
            - ~/.aspnet/https:/https:ro
    api-articulos:
        image: api-articulos
        build: 
            context: ./ApiArticulos
            dockerfile: Dockerfile
        ports:
            - 6100:80
            - 6101:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development 
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=tuk1
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.vsdbg:/remote_debbuger.rw
            - ~/.aspnet/https:/https:ro
