version: '3.4'

services:
    transactions-api: 
        image: transactions-api
        build: 
            context: ./Tuki.Transactions.Api
            dockerfile: Dockerfile
        ports: 
            - 6000:80
            - 6001:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development 
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=tuk1
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.vsdbg:/remote_debbuger.rw
            - ~/.aspnet/https:/https:ro
    catalogs-api:
        image: catalogs-api 
        build: 
            context: ./Tuki.Catalogs.Api
            dockerfile: Dockerfile
        ports:
            - 6100:80
            - 6101:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development 
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=tuk1
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.vsdbg:/remote_debbuger.rw
            - ~/.aspnet/https:/https:ro
