version: '3.9'

networks:
  app-network-public:
    driver: bridge

volumes:
  sql-server-data:
    driver: local
  sqldata:
  sqllog:
  sqlbackup:

services:
    tuki-db:
        image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
        container_name: tuki-db
        networks:
        - app-network-public
        restart: always
        env_file:
        - sqlserver.env
        - sapassword.env
        ports:
        - 1433:1433
        volumes:
        - sql-server-data:/var/opt/mssql/
        - sqldata:/var/opt/sqlserver/data
        - sqllog:/var/opt/sqlserver/log
        - sqlbackup:/var/opt/sqlserver/backup
        - /c/docker/shared:/usr/shared
    transactions-api: 
        image: transactions-api
        build: 
            context: ../src/Tuki.Transactions.Api
            dockerfile: Dockerfile
            args:
                - NUGET_USERNAME=i-badell
                - NUGET_PASSWORD=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
        ports: 
            - 6000:80
            - 6001:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development 
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=tuk1
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.vsdbg:/remote_debbuger.rw
            - ~/.aspnet/https:/https:ro
    catalogs-api:
        image: catalogs-api 
        build: 
            context: ../src/Tuki.Catalogs.Api
            dockerfile: Dockerfile
            args:
                - NUGET_USERNAME=i-badell
                - NUGET_PASSWORD=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
        ports:
            - 6100:80
            - 6101:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development 
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=tuk1
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.vsdbg:/remote_debbuger.rw
            - ~/.aspnet/https:/https:ro
