on: 
  pull_request:
    branches:
      - 'main'
    paths:
      - './Tuki.Common/**'
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set directory
      working-directory: ./Tuki.Common
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build project
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test project
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack nuget
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output 
    - name: Push nuget
      run: dotnet nuget push Tuki.Common.${VERSION}.nupkg --source https://nuget.pkg.github.com/tukiuy/index.json --api-key ${GITHUB_TOKEN}
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


